# Netlify configuration for Nashie Locksmiths

[build]
  command = "npm run build"
  publish = "build"

[functions]
  directory = "netlify/functions"

[dev]
  command = "npm start"
  port = 3000
  targetPort = 3000
  framework = "#custom"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
